#!/usr/bin/env python3

import sys, os

sys.path.insert(1,os.path.join(os.path.dirname(os.path.realpath(__file__)), 'lib/'))

import epd7in5_V2

epd = epd7in5_V2.EPD()
epd.init()
epd.sleep()
epd.Dev_exit()

